/*
 * ch20_network_reconstructed.h
 *
 * Header reconstructed by decompilation of the server_O2_strip binary
 * Reverse Engineering Training — Chapter 20, Checkpoint
 *
 * Source binary: server_O2_strip
 *                SHA256: (to be filled with your binary's hash)
 * Primary tool:  Ghidra 11.x
 * Secondary tool: RetDec 5.0
 *
 * ====================================================================
 * CUSTOM NETWORK PROTOCOL — OVERVIEW
 * ====================================================================
 *
 * Transport: TCP, port 4337
 * Model:     client/server, 1 client at a time (blocking accept)
 *
 * Frame format:
 *
 *   +--------+--------+---------+------+------------------+---------+
 *   | magic  | magic  | version | type | payload_len (BE) | payload | chksum |
 *   | 0xC0   | 0xFE   |  0x01   | 1B   |     2B           |  N B    |  1B    |
 *   +--------+--------+---------+------+------------------+---------+
 *   |<------------- HEADER (6 bytes) -------------->|      |         |
 *
 * Checksum: XOR of all bytes in header + payload.
 *
 * Typical flow:
 *   1. Client connects via TCP
 *   2. Client sends AUTH_REQ (username + password hash)
 *   3. Server responds AUTH_RESP (success/failure + session token)
 *   4. Client sends CMD_REQ (token + command + arguments)
 *   5. Server responds CMD_RESP (data)
 *   6. Repeat 4-5 as needed
 *   7. Client sends DISCONNECT or closes the connection
 *
 * The server also supports PING/PONG for keepalive.
 *
 * ====================================================================
 * ANALYSIS NOTES
 * ====================================================================
 *
 * - Credentials are hardcoded in .rodata:
 *     username = "admin"
 *     password hash = 32-byte array at address 0x4040XX
 *   The hash is computed client-side by an algorithm based on FNV-1a
 *   iterated 32 times (one output byte per round). Original password
 *   not recovered through static analysis alone.
 *
 * - The session token is generated by an LCG (Linear Congruential
 *   Generator) with fixed seed 0xCAFEBABE and classic glibc parameters
 *   (a=1103515245, c=12345). The token is therefore deterministic
 *   and predictable — intentional vulnerability.
 *
 * - The payload_len field is big-endian (network byte order).
 *   The conversion functions are inlined by GCC at -O2 and
 *   appear as shifts/OR in the pseudo-code.
 *
 * ====================================================================
 */

#ifndef CH20_NETWORK_RECONSTRUCTED_H
#define CH20_NETWORK_RECONSTRUCTED_H

#include <stdint.h>
#include <stddef.h>

/* ====================================================================
 * Section 1: Protocol Constants
 *
 * Sources:
 *   - Magic bytes   : comparison in recv_message (FUN_00401340)
 *   - Version       : comparison in recv_message
 *   - Sizes         : arguments to memcmp, recv, loops
 *   - Port          : argument to htons() in main()
 * ==================================================================== */

/* Magic bytes — first bytes of each frame, verified upon reception.
 * Identified by the comparison:
 *   if (header[0] != 0xC0 || header[1] != 0xFE) return -1;
 * in the recv_message function. */
#define PROTO_MAGIC_0       0xC0
#define PROTO_MAGIC_1       0xFE

/* Protocol version — third byte of the header.
 * Identified by the comparison:
 *   if (header[2] != 0x01) { fprintf(stderr, "Unsupported version..."); }
 */
#define PROTO_VERSION       0x01

/* Maximum payload size — deduced from the test:
 *   if (payload_len > 0x400) return -1;
 * in recv_message, and from the local buffer size (1024 bytes). */
#define PROTO_MAX_PAYLOAD   1024

/* Protocol header size — number of bytes read by the first
 * recv_all() in recv_message: recv_all(fd, hdr, 6). */
#define PROTO_HEADER_SIZE   6

/* Session token size — deduced from:
 *   - the generation loop: for (i = 0; i < 16; i++)
 *   - the memcmp argument in handle_cmd: memcmp(token, session, 16)
 *   - the token field size in auth_resp: 16 bytes after success */
#define PROTO_TOKEN_LEN     16

/* Authentication hash size — deduced from:
 *   - the memcmp argument in handle_auth: memcmp(hash, valid_hash, 32)
 *   - the VALID_HASH array size in .rodata: 32 bytes */
#define PROTO_HASH_LEN      32

/* Default listening port — argument to htons() in main().
 * htons(0x10F1) = htons(4337). */
#define DEFAULT_PORT        4337

/* ====================================================================
 * Section 2: Enumerations
 * ==================================================================== */

/*
 * Message types — identified in the main dispatcher's switch
 * (handle_client / FUN_00401780).
 *
 * The switch tests the type field (offset 3 in header):
 *   case 0x01 → calls handle_auth     → AUTH_REQ
 *   case 0x03 → calls handle_cmd      → CMD_REQ
 *   case 0x05 → sends response type 6 → PING (replied with PONG)
 *   case 0xFF → printf("disconnected") + return → DISCONNECT
 *   default   → fprintf(stderr, "Unknown type") → ignored
 *
 * Types 0x02, 0x04, 0x06 are not in the switch because they are
 * messages SENT by the server (responses), not received.
 * Their values are deduced from the 'type' argument passed to
 * send_message in the corresponding handlers.
 */
typedef enum {
    MSG_AUTH_REQ    = 0x01,   /* client → server: authentication request */
    MSG_AUTH_RESP   = 0x02,   /* server → client: authentication response */
    MSG_CMD_REQ     = 0x03,   /* client → server: command request */
    MSG_CMD_RESP    = 0x04,   /* server → client: command response */
    MSG_PING        = 0x05,   /* client → server: keepalive */
    MSG_PONG        = 0x06,   /* server → client: keepalive response */
    MSG_DISCONNECT  = 0xFF    /* client → server: end of session */
} msg_type_t;

/*
 * Command identifiers — identified in the command handler's switch
 * (handle_cmd / FUN_00401620).
 *
 * The switch tests the cmd_id field (offset 16 in the CMD_REQ payload,
 * i.e. right after the 16-byte token):
 *   case 0x10 → reads arg_len, returns payload as-is   → ECHO
 *   case 0x03 → sends a server info string              → GET_INFO
 *   case 0x01 → sends a list of file names              → LIST_FILES
 *   case 0x02 → sends a file's content (FLAG)           → READ_FILE
 *   default   → sends "ERR:UNKNOWN_CMD"                 → unhandled
 *
 * The response strings in .rodata ("config.dat\nusers.db\n...",
 * "FLAG{...}", "KeyGenMe Training Server v1.0...") confirm the
 * semantics of each command.
 */
typedef enum {
    CMD_LIST_FILES  = 0x01,   /* list available files */
    CMD_READ_FILE   = 0x02,   /* read a file's content */
    CMD_GET_INFO    = 0x03,   /* get server information */
    CMD_ECHO        = 0x10    /* echo: returns arguments as-is */
} cmd_id_t;

/* ====================================================================
 * Section 3: Data Structures
 *
 * All network structures are packed (no padding) —
 * confirmed by consecutive access offsets in the pseudo-code
 * and by the total recv/send sizes.
 * ==================================================================== */

/*
 * Protocol header — 6 bytes, packed.
 *
 * Identified in recv_message (FUN_00401340):
 *   recv_all(fd, hdr_buf, 6);
 *   if (hdr_buf[0] != 0xC0 || hdr_buf[1] != 0xFE) → magic
 *   if (hdr_buf[2] != 0x01)                        → version
 *   type = hdr_buf[3];                              → type
 *   plen = (hdr_buf[4] << 8) | hdr_buf[5];         → payload_len (BE)
 *
 * Verified layout:
 *   offset 0x00 : magic[0]      (1 byte)
 *   offset 0x01 : magic[1]      (1 byte)
 *   offset 0x02 : version       (1 byte)
 *   offset 0x03 : type          (1 byte)
 *   offset 0x04 : payload_len   (2 bytes, big-endian)
 *   total: 6 bytes ✓
 */
typedef struct __attribute__((packed)) {
    uint8_t  magic[2];       /* offset 0x00 — expected: {0xC0, 0xFE} */
    uint8_t  version;        /* offset 0x02 — expected: 0x01 */
    uint8_t  type;           /* offset 0x03 — msg_type_t */
    uint16_t payload_len;    /* offset 0x04 — big-endian! */
} proto_header_t;

/*
 * AUTH_REQ payload — sent by client for authentication.
 *
 * Identified in handle_auth (FUN_00401500):
 *   strncmp(payload + 0x00, VALID_USER, 32)  → username, 32 bytes
 *   memcmp(payload + 0x20, VALID_HASH, 32)   → hash, 32 bytes
 *
 * Offset 0x20 = 32 confirms that username is 32 bytes (not 64).
 * The username field is compared with strncmp, so it's a
 * NUL-terminated string (or truncated to 32 characters).
 *
 * Verified layout:
 *   offset 0x00 : username[32]       (32 bytes)
 *   offset 0x20 : password_hash[32]  (32 bytes)
 *   total: 64 bytes ✓
 *   Confirmed by the test: if (plen < 64) → rejection
 */
typedef struct __attribute__((packed)) {
    char    username[32];                  /* offset 0x00 — NUL-terminated string */
    uint8_t password_hash[PROTO_HASH_LEN]; /* offset 0x20 — password hash */
} auth_req_payload_t;

/*
 * AUTH_RESP payload — sent by server in response to AUTH_REQ.
 *
 * Identified in handle_auth (FUN_00401500), success branch:
 *   resp_buf[0] = 1;                           → success (1 byte)
 *   memcpy(resp_buf + 1, session_token, 16);   → token (16 bytes)
 *   send_message(fd, 0x02, resp_buf, 17);      → total size = 17
 *
 * Failure branch:
 *   resp_buf[0] = 0;
 *   send_message(fd, 0x02, resp_buf, 17);      → same size, token = 0
 *
 * Verified layout:
 *   offset 0x00 : success         (1 byte: 0x00=fail, 0x01=ok)
 *   offset 0x01 : token[16]       (16 bytes, valid iff success==1)
 *   total: 17 bytes ✓
 */
typedef struct __attribute__((packed)) {
    uint8_t success;                   /* offset 0x00 — 0x00=failure, 0x01=success */
    uint8_t token[PROTO_TOKEN_LEN];    /* offset 0x01 — session token (if success) */
} auth_resp_payload_t;

/*
 * CMD_REQ payload header — sent by client for a command.
 *
 * Identified in handle_cmd (FUN_00401620):
 *   memcmp(payload + 0x00, session_token, 16)  → token, 16 bytes
 *   cmd_id = payload[0x10];                     → cmd_id, 1 byte
 *   arg_len = (payload[0x11] << 8) | payload[0x12]; → arg_len, 2 bytes BE
 *
 * The command arguments follow this header immediately in the
 * payload, spanning arg_len bytes.
 *
 * Verified layout:
 *   offset 0x00 : token[16]     (16 bytes)
 *   offset 0x10 : cmd_id        (1 byte — cmd_id_t)
 *   offset 0x11 : arg_len       (2 bytes, big-endian)
 *   total header: 19 bytes, followed by arg_len bytes of arguments
 */
typedef struct __attribute__((packed)) {
    uint8_t  token[PROTO_TOKEN_LEN];  /* offset 0x00 — session token */
    uint8_t  cmd_id;                  /* offset 0x10 — cmd_id_t */
    uint16_t arg_len;                 /* offset 0x11 — big-endian */
    /* followed by arg_len bytes of arguments */
} cmd_req_header_t;

/* ====================================================================
 * Section 4: Inline Utility Functions
 *
 * These functions are inlined by GCC at -O2 and have no dedicated
 * address in the binary. They are reconstructed from recurring
 * instruction patterns in send_message and recv_message.
 * ==================================================================== */

/*
 * XOR checksum — identified in send_message and recv_message.
 *
 * The assembly pattern is a loop:
 *   xor al, [rsi + rcx]  ;  inc rcx  ;  cmp rcx, rdx  ;  jb loop
 * The result is a cumulative XOR of all bytes in the buffer.
 *
 * Used to compute the checksum of the complete frame
 * (header + payload), stored in the last byte of the frame.
 */
static inline uint8_t proto_checksum(const uint8_t *data, size_t len)
{
    uint8_t sum = 0;
    for (size_t i = 0; i < len; i++)
        sum ^= data[i];
    return sum;
}

/*
 * 16-bit big-endian read — identified by the pattern:
 *   movzx eax, byte ptr [rdi]
 *   shl   eax, 8
 *   movzx ecx, byte ptr [rdi+1]
 *   or    eax, ecx
 * in recv_message (payload_len extraction) and handle_cmd
 * (arg_len extraction).
 */
static inline uint16_t read_be16(const uint8_t *p)
{
    return ((uint16_t)p[0] << 8) | (uint16_t)p[1];
}

/*
 * 16-bit big-endian write — identified by the pattern:
 *   mov byte ptr [rdi], ah     (or shr eax, 8 + mov)
 *   mov byte ptr [rdi+1], al
 * in send_message (payload_len writing in the header).
 */
static inline void write_be16(uint8_t *p, uint16_t val)
{
    p[0] = (uint8_t)(val >> 8);
    p[1] = (uint8_t)(val & 0xFF);
}

/* ====================================================================
 * Section 5: Main Function Signatures
 *
 * The addresses are those observed in server_O2_strip.
 * They will vary if the binary is recompiled.
 *
 * Convention: functions are listed in call order
 * from main() → handle_client() → specific handlers.
 * ==================================================================== */

/*
 * send_all — complete buffer send on a socket.
 * Loops on send() until all bytes are sent.
 * Returns the number of bytes sent, or -1 on error.
 *
 * Identified by: while loop around send(), parameters (fd, buf, len).
 * FUN_00401120
 */
/* ssize_t send_all(int fd, const uint8_t *buf, size_t len); */

/*
 * recv_all — complete reception of exactly len bytes.
 * Loops on recv() until the buffer is filled.
 * Returns the number of bytes received, or -1 on error/disconnection.
 *
 * Identified by: while loop around recv(), same pattern as send_all.
 * FUN_00401180
 */
/* ssize_t recv_all(int fd, uint8_t *buf, size_t len); */

/*
 * send_message — send a complete protocol message.
 *
 * Builds a frame: header (6 bytes) + payload + checksum (1 byte).
 * Writes magic bytes, version, type and payload_len (BE) in the
 * header, copies the payload, computes the XOR checksum, and sends
 * everything via send_all.
 *
 * Returns 0 on success, -1 on error.
 *
 * Identified by: writing 0xC0/0xFE at buffer start,
 * call to proto_checksum (inlined), then send_all.
 * FUN_00401250
 */
int send_message(int fd, uint8_t type,
                 const uint8_t *payload, uint16_t payload_len);

/*
 * recv_message — receive a complete protocol message.
 *
 * Reads the header (6 bytes) via recv_all, verifies magic bytes and
 * version, extracts type and payload_len. If payload_len > 0,
 * reads the payload. Reads the final checksum (1 byte) and verifies it.
 *
 * Output parameters: type, payload (caller-provided buffer),
 * payload_len.
 * Returns 0 on success, -1 on error.
 *
 * Identified by: recv_all(fd, hdr, 6), magic/version comparisons,
 * BE extraction of payload_len, conditional second recv_all.
 * FUN_00401340
 */
int recv_message(int fd, uint8_t *type,
                 uint8_t *payload, uint16_t *payload_len);

/*
 * generate_token — session token generation.
 *
 * Uses an LCG (Linear Congruential Generator):
 *   seed = 0xCAFEBABE
 *   loop 16 times: seed = seed * 1103515245 + 12345
 *                  token[i] = (seed >> 16) & 0xFF
 *
 * The seed is FIXED — the token is identical for every connection.
 * Intentional vulnerability for the RE exercise.
 *
 * Identified by: constant 0xCAFEBABE, multiplier 1103515245
 * (classic glibc LCG), 16-iteration loop.
 * FUN_004014a0
 */
void generate_token(uint8_t *token);

/*
 * handle_auth — process an authentication request.
 *
 * Verifies that the payload is long enough (>= 64 bytes).
 * Compares the username with the hardcoded credential via strncmp.
 * Compares the hash with the hardcoded hash via memcmp (32 bytes).
 * If both match:
 *   - generates a token via generate_token()
 *   - sends AUTH_RESP with success=1 and the token
 * Otherwise:
 *   - sends AUTH_RESP with success=0
 *
 * Identified by: strncmp + memcmp calls on the payload,
 * references to .rodata data (username + hash), call to
 * generate_token, sending a type 0x02 message.
 * FUN_00401500
 */
void handle_auth(int fd, const uint8_t *payload, uint16_t payload_len);

/*
 * handle_cmd — process a command request.
 *
 * Verifies that the payload is long enough (>= 19 bytes, size of
 * cmd_req_header_t). Verifies the session token via memcmp.
 * If the token is invalid, sends "ERR:NOT_AUTH".
 * Otherwise, dispatches based on cmd_id:
 *   CMD_ECHO (0x10)       → returns the arguments as-is
 *   CMD_GET_INFO (0x03)   → returns the server identification string
 *   CMD_LIST_FILES (0x01) → returns a list of file names
 *   CMD_READ_FILE (0x02)  → returns a file's content (contains the FLAG)
 *   default               → returns "ERR:UNKNOWN_CMD"
 *
 * Identified by: memcmp on the first 16 bytes of payload
 * (token), switch on the byte at offset 16 (cmd_id), sending
 * type 0x04 messages.
 * FUN_00401620
 */
void handle_cmd(int fd, const uint8_t *payload, uint16_t payload_len);

/*
 * handle_client — main loop for handling a connected client.
 *
 * Resets the authentication state to zero, then loops on
 * recv_message. Dispatches based on message type:
 *   MSG_AUTH_REQ (0x01)   → handle_auth
 *   MSG_CMD_REQ (0x03)    → handle_cmd
 *   MSG_PING (0x05)       → sends MSG_PONG (0x06) with no payload
 *   MSG_DISCONNECT (0xFF) → return (clean exit)
 *   default               → log "Unknown type" and continue
 *
 * Identified by: while loop around recv_message, switch
 * on type, calls to the handlers above.
 * FUN_00401780
 */
void handle_client(int client_fd);

/* ====================================================================
 * Notable hardcoded data (in .rodata)
 *
 * This data is not part of the API but is documented here for
 * reference as it is necessary for writing a functional client.
 * ==================================================================== */

/*
 * Valid username: "admin" (string in .rodata)
 *
 * Valid password hash (32 bytes in .rodata):
 *   0xa7, 0x5f, 0x5a, 0x35, 0x8f, 0xc1, 0xbc, 0x8e,
 *   0xab, 0xa8, 0x4f, 0xd3, 0xc7, 0x6d, 0xb6, 0x8e,
 *   0xa1, 0xe6, 0xab, 0x71, 0xef, 0x77, 0x5c, 0x2f,
 *   0x82, 0x04, 0xf8, 0xcd, 0xbc, 0x07, 0x47, 0x2d
 *
 * The password hashing algorithm is not implemented server-side —
 * only the final hash is compared. To authenticate, a client can
 * send these 32 bytes directly without knowing the original password.
 *
 * Response strings identified in .rodata:
 *   - "KeyGenMe Training Server v1.0 -- RE Training GCC"  (CMD_GET_INFO)
 *   - "config.dat\nusers.db\nsecret.key\nlog.txt"          (CMD_LIST_FILES)
 *   - "FLAG{pr0t0c0l_r3v3rs3d_gcc}\n"                      (CMD_READ_FILE)
 *   - "ERR:NOT_AUTH"                                         (invalid token)
 *   - "ERR:UNKNOWN_CMD"                                      (unknown command)
 */

#endif /* CH20_NETWORK_RECONSTRUCTED_H */
